'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
const api = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';
type Member = { id: number; name: string; role: string; bio: string; order: number };
type Event = { id: number; title: string; description: string; date: string; location: string; published: boolean };
export default function Admin() {
  const [allowed, setAllowed] = useState(false); const [message, setMessage] = useState('Vérification de la session…');
  const [members, setMembers] = useState<Member[]>([]); const [events, setEvents] = useState<Event[]>([]);
  const [editMember, setEditMember] = useState<Member | null>(null); const [editEvent, setEditEvent] = useState<Event | null>(null);
  const router = useRouter();
  async function request(path: string, options?: RequestInit) { return fetch(`${api}${path}`, { credentials: 'include', ...options }); }
  async function refresh() { const [m, e] = await Promise.all([request('/api/members'), request('/api/admin/events')]); if (m.ok && e.ok) { setMembers(await m.json()); setEvents(await e.json()); } }
  useEffect(() => { request('/api/me').then(r => r.json()).then(data => { if (data.user?.role === 'ADMIN') { setAllowed(true); setMessage(''); refresh(); } else setMessage('Connectez-vous avec un compte administrateur.'); }).catch(() => setMessage('API indisponible.')); }, []);
  async function saveMember(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const data = { name: f.get('name'), role: f.get('role'), bio: f.get('bio'), order: Number(f.get('order')) }; const r = await request(`/api/admin/members${editMember ? `/${editMember.id}` : ''}`, { method: editMember ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); setMessage(r.ok ? 'Membre enregistré.' : 'Impossible d’enregistrer ce membre.'); if (r.ok) { setEditMember(null); e.currentTarget.reset(); refresh(); router.refresh(); } }
  async function saveEvent(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const data = { title: f.get('title'), description: f.get('description'), location: f.get('location'), date: new Date(String(f.get('date'))).toISOString(), published: f.get('published') === 'on' }; const r = await request(`/api/admin/events${editEvent ? `/${editEvent.id}` : ''}`, { method: editEvent ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); setMessage(r.ok ? 'Événement enregistré.' : 'Impossible d’enregistrer cet événement.'); if (r.ok) { setEditEvent(null); e.currentTarget.reset(); refresh(); } }
  async function remove(type: 'members' | 'events', id: number) { if (!window.confirm('Supprimer cet élément ?')) return; const r = await request(`/api/admin/${type}/${id}`, { method: 'DELETE' }); setMessage(r.ok ? 'Élément supprimé.' : 'Suppression impossible.'); if (r.ok) refresh(); }
  return <section className="section"><p className="eyebrow dark">Gestion de la liste</p><h1>Administration</h1><p role="status" aria-live="polite">{message}</p>{!allowed ? <a href="/connexion">Aller à la connexion</a> : <><button type="button" className="secondary" onClick={async () => { await request('/api/logout', { method: 'POST' }); location.href = '/'; }}>Se déconnecter</button><div className="admin-grid"><section aria-labelledby="members-title"><h2 id="members-title">Membres</h2><form className="panel" onSubmit={saveMember} key={editMember?.id || 'new-member'}><h3>{editMember ? 'Modifier un membre' : 'Ajouter un membre'}</h3><label>Nom<input name="name" defaultValue={editMember?.name} required maxLength={80} /></label><label>Rôle<input name="role" defaultValue={editMember?.role} required maxLength={80} /></label><label>Présentation<textarea name="bio" defaultValue={editMember?.bio} maxLength={600} /></label><label>Ordre d’affichage<input name="order" type="number" defaultValue={editMember?.order || 0} /></label><button>Enregistrer</button>{editMember && <button className="secondary" type="button" onClick={() => setEditMember(null)}>Annuler</button>}</form><ul className="manage-list">{members.map(m => <li key={m.id}><span><strong>{m.name}</strong> · {m.role}</span><span><button className="secondary" onClick={() => setEditMember(m)}>Modifier</button><button className="danger" onClick={() => remove('members', m.id)}>Supprimer</button></span></li>)}</ul></section><section aria-labelledby="events-title"><h2 id="events-title">Événements</h2><form className="panel" onSubmit={saveEvent} key={editEvent?.id || 'new-event'}><h3>{editEvent ? 'Modifier un événement' : 'Ajouter un événement'}</h3><label>Titre<input name="title" defaultValue={editEvent?.title} required maxLength={120} /></label><label>Date et heure<input name="date" type="datetime-local" defaultValue={editEvent?.date ? new Date(editEvent.date).toLocaleString('sv-SE', { timeZone: 'Europe/Paris' }).replace(' ', 'T').slice(0, 16) : ''} required /></label><label>Lieu<input name="location" defaultValue={editEvent?.location} required maxLength={160} /></label><label>Description<textarea name="description" defaultValue={editEvent?.description} required maxLength={3000} /></label><label className="check"><input name="published" type="checkbox" defaultChecked={editEvent?.published} /> Publier l’événement</label><button>Enregistrer</button>{editEvent && <button className="secondary" type="button" onClick={() => setEditEvent(null)}>Annuler</button>}</form><ul className="manage-list">{events.map(e => <li key={e.id}><span><strong>{e.title}</strong> · {e.published ? 'Publié' : 'Brouillon'}</span><span><button className="secondary" onClick={() => setEditEvent(e)}>Modifier</button><button className="danger" onClick={() => remove('events', e.id)}>Supprimer</button></span></li>)}</ul></section></div></>}</section>;
}
